name: SQL Server Deployment

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download DACPAC
      run: |
        # Replace 'dacpacs/bid.dacpac' with the correct path in your repository
        curl -LJO https://github.com/kbsoftware-jan/GitHubActionTest.git/raw/main/dacpacs/*
      shell: cmd

    - name: Deploy to SQL Server
      run: |
        SqlPackage.exe /a:publish /tsn:"localhost" /tdn:"BiD.Net" /sf:"dacpacs/bid.dacpac" /p:RegisterDataTierApplication=true /p:BlockWhenDriftDetected=false /ttsc:"True"
      shell: cmd
