name: SQL Server Deployment

on:
  workflow_dispatch

env:
############ Replace the variables with your values! #############
  GITHUB_REPOSITORY: "https://github.com/kbsoftware-jan/GitHubActionTest"
  GITHUB_FOLDER_NAME: "dacpacs"
  DATABASE_NAME: "BiD.Net"
  DATABASE_DACPAC: "bid.dacpac"
####################################################


jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download DACPAC
      run: |
        # Replace 'dacpacs/bid.dacpac' with the correct path in your repository
        curl -LJO ${{ env.GITHUB_REPOSITORY}}/raw/main/${{ env.GITHUB_FOLDER_NAME}}/*
      shell: cmd

    - name: Deploy to SQL Server
      run: |
        SqlPackage.exe /a:publish /tsn:"localhost" /tdn:${{ env.DATABASE_NAME}} /sf:${{ env.GITHUB_FOLDER_NAME}}/${{ env.DATABASE_DACPAC}} /p:RegisterDataTierApplication=true /p:BlockWhenDriftDetected=false /ttsc:"True"
      shell: cmd
