
name: My .NET Action

on:
  workflow_dispatch

jobs:
  build:
    runs-on: self-hosted
    
    defaults:
      run:
        shell: cmd

    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Stop example.com
      #run: iisreset /stop /server:PublishASPCoreTest
      run: cmd /c %windir%\syswow64\inetsrv\appcmd stop site /site.name:PublishASPCoreTest
    - name: Publish Release
      run: dotnet publish GitHubActionTest --configuration Release -o C:\www\PublishASPCoreTest
    - name: Start example.com
      run: cmd /c %windir%\syswow64\inetsrv\appcmd start site /site.name:PublishASPCoreTest
