name: Deploy to IIS
on:
  workflow_dispatch
env:
  # SERVER_NAME: "GithubServer"
  SERVER_NAME: "PublishASPCoreTest"
  GITHUB_FOLDER_NAME: "GitHubActionTest"
  FILE_PATH: "C:/www/PublishASPCoreTest"
  # FILE_PATH: "C:/Users/JanKalina/Documents/GithubRunnerTest/www/GithubServer"

jobs:
  build:
    runs-on: self-hosted
    
    defaults:
      run:
        shell: cmd
    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Stop server
      run: cmd /c %windir%\syswow64\inetsrv\appcmd stop site /site.name:${{ env.SERVER_NAME}}
    - name: Publish Release
      run: dotnet publish ${{ env.GITHUB_FOLDER_NAME}} --configuration Release -o ${{ env.FILE_PATH}}
    - name: Start server
      run: cmd /c %windir%\syswow64\inetsrv\appcmd start site /site.name:${{ env.SERVER_NAME}}
