# name: .NET Core Deploy to IIS

# on: 
#   workflow_dispatch

# jobs: 
#   build-and-deploy:

#     runs-on: self-hosted

#     steps: 
#      - uses: actions/checkout@v2

#      - name: Setup .NET Core
#        uses: actions/setup-dotnet@v1
#        with:
#          dotnet-version: '7.0.x'

#      - name: Build with dotnet
#        shell: cmd
#        run: dotnet build --configuration Release

#      - name: dotnet publish
#        shell: cmd
#        run: |
#          dotnet public -c Release -o .\myapp
     
#      - name: Deploy to IIS
#        shell: cmd
#        run: |
#          iisreset /stop
#          xcopy /s /y .\myapp\* c:\www\PublishASPCoreTest
#          iisreset /start

name: My .NET Action

on:
  workflow_dispatch

jobs:
  build:
    runs-on: self-hosted
    
    defaults:
      run:
        shell: cmd

    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Stop example.com
      run: iisreset /stop
    - name: Publish Release
      run: dotnet publish GitHubActionTest --configuration Release -o C:\www\PublishASPCoreTest
    - name: Start example.com
      run: iisreset /start
