name: Windows Service Deployment

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted

     steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Change Path to .NET Framework and Deploy Windows Service
       run: |
        cd "C:\Windows\Microsoft.NET\Framework\v4.0.30319" && \
        net stop GitWinService || true && \
        installUtil.exe /u "C:\Users\hp\source\repos\GithubWinService\GithubWinService\bin\Debug\GitWinService.exe" || true && \
        curl -LJO https://github.com/kbsoftware-jan/GitHubActionTest.git/raw/main/WindowsService/* && \
        xcopy /E /Y "${GITHUB_WORKSPACE}\WindowsService\*" "C:\Users\hp\source\repos\GithubWinService\GithubWinService\bin\Debug" && \
        installUtil.exe "C:\Users\hp\source\repos\GithubWinService\GithubWinService\bin\Debug\GithubWinService.exe" && net start GitWinService
      shell: cmd
