name: Windows Service Deployment

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted
    env:
    ############ Replace the variables with your values! #############
      SERVICE_NAME: "service1"
      GITHUB_FOLDER_NAME: "WindowsService"
      SERVICE_FOLDER_PATH: "C:/Users/JanKalina/Documents/GithubRunnerTest/WindowsService"
      EXE_NAME: "GithubWinService.exe"
    ####################################################

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test
      run: echo $SERVICE_FOLDER_PATH

    - name: Stop and Uninstall Existing Service
      run: |
        net stop $SERVICE_NAME || echo Service was already stoped
        sc delete $SERVICE_NAME || echo Service was already deleted
      shell: cmd

    - name: Copy Folder to Local Machine
      run: |
        Copy-Item -Path $GITHUB_FOLDER_NAME\* -Destination $SERVICE_FOLDER_PATH -Recurse

    - name: Install and Start New Service
      run: |
        "C:\Windows\Microsoft.NET\Framework\v4.0.30319\installUtil.exe" $SERVICE_FOLDER_PATH\$EXE_NAME && net start $SERVICE_NAME
      shell: cmd



