name: Windows Service Deployment

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted
    env:
    ############ Replace the variables with your values! #############
      SERVICE_NAME: "service1"
      GITHUB_FOLDER_NAME: "WindowsService"
      SERVICE_FOLDER_PATH: "C:/Users/JanKalina/Documents/GithubRunnerTest/WindowsService"
      EXE_NAME: "GithubWinService.exe"
    ####################################################

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Stop and Uninstall Existing Service
      run: |
        net stop ${{ env.SERVICE_NAME}} || echo Service was already stoped
        sc delete ${{ env.SERVICE_NAME}} || echo Service was already deleted
      shell: cmd

    - name: Copy Folder to Local Machine
      run: |
        Copy-Item -Path ${{ env.GITHUB_FOLDER_NAME}}\* -Destination ${{ env.SERVICE_FOLDER_PATH}} -Recurse

    - name: Install and Start New Service
      run: |
        "C:\Windows\Microsoft.NET\Framework\v4.0.30319\installUtil.exe" ${{ env.SERVICE_FOLDER_PATH}}\${{ env.EXE_NAME}} && net start ${{ env.SERVICE_NAME}}
      shell: cmd



