name: Windows Service Deployment

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Stop and Uninstall Existing Service
    #   run: |
    #     net stop service1 || echo Service was already stoped
    #     sc delete service1 || echo Service was already deleted
    #   shell: cmd

    - name: Copy Folder to Local Machine
      run: |
        Copy-Item -Path WindowsService\* -Destination "C:\Users\hp\source\repos\GithubWinService\GithubWinService\bin\Debug" -Recurse

    - name: Install and Start New Service
      run: |
        "C:\Windows\Microsoft.NET\Framework\v4.0.30319\installUtil.exe" "C:\Users\hp\source\repos\GithubWinService\GithubWinService\bin\Debug\GithubWinService.exe" && net start service1
      shell: cmd



